### PR TITLE
fixed jumping navigation on scroll

### PR DESCRIPTION
**Pull request by stffndk**
Moved the .sticky class from the .menu-container to the .container
element and added matching padding-top to prevent the whole page to
jump when scrolling

### CODE REVIEW

**Comment by Thelle** [comment]
Jumping navigation was identified with newest Chrome ( 39.0.2171.95) on Windows @ksmandersen - have not noticed it on mac..

**Comment by stffndk** [comment]
I see it in Chrome/OSX
Scroll down a pixel or two and the `.header-container` jumps up

**Comment by Thelle** [comment]
Arr - ok - see it now! Just didn't notice :)

**Comment by Thelle** [comment]
Arr ok I see it now! - Just didn't notice - thought it was jumping down the sections or something :) I'll let Kristian be in charge of the merge. Thank you so much for the fix @stffndk!

**Comment by stffndk** [comment]
You're welcome.
Small cosmetic bug, but first thing that caught my eye.
Also a small fix

**Comment by ksmandersen** [comment]
Looks great :+1:

Have you verified that this doesn't cause an issue on iOS?

**Comment by stffndk** [comment]
I don't see anything iOS specific here.
There is some mediaqueries — haven't touched those.

**Pull request merged**
