### PR TITLE
Added "contribute" link to the help page

### PR DESCRIPTION
**Pull request by higiacomo**
https://github.com/bemyeyes/bemyeyes-website/issues/58#issuecomment-121202880

### CODE REVIEW

**Comment by ksmandersen** [comment]
Did you check out how this looks on smaller screens like iOS? Not sure the menu will fit with another link in there

**Comment by higiacomo** [comment]
You're right, forgot to check that sorry

Can I integrate something like this to have a mobile navigation?
http://responsive-nav.com/
It's very compatible, lightweight and accessible

**Comment by duemunk** [comment]
I don't like hamburgers on websites. I usually only visit once, so I don't know if I should scroll, or open menu to do something.
I prefer a small menu if possible, else keep things as a one-pager with big sections. Just throw in some white space.

**Comment by ksmandersen** [comment]
Yeah, I agree. Hamburger menus on iOS really arent that great. Either we should eliminate another link or make the menu spread over two lines like we do on http://robo.cat/

**Comment by duemunk** [comment]
Multiline menu would be great!

**Comment by higiacomo** [comment]
All right I'll make it multiline

**Comment by higiacomo** [comment]
Something like this?

screen shot 2015-07-23 at 18 23 09

**Comment by duemunk** [comment]
Great! The items seems a bit small, but it's hard for me to judge.
In general, having target close to each other in both dimensions requires a bit extra margin for error.

**Comment by ksmandersen** [comment]
I think that looks good

**Comment by higiacomo** [comment]
All right, now it's on 2 lines, same as screenshot above. I'll let you merge when you want

**Comment by ksmandersen** [comment]
Pushed live now

**Pull request merged**
